### ISSUE TITLE
Error executing DDL via JDBC Statement

### ISSUE THREAD

**Issue by daydaywritecode** [TeamAndCreator/bambootattan_server#20]
### Problem description:
After I run the program,the following error message appears:
![image](https://user-images.githubusercontent.com/43334761/48556758-c600cf80-e91f-11e8-8ee3-42fa3d62f735.png)
Which say:
**Error executing DDL via JDBC Statement**
`2018-11-15 21:03:21.772  WARN 9872 --- [           main] o.h.t.s.i.ExceptionHandlerLoggedImpl     : 
GenerationTarget encountered exception accepting command : Error executing DDL via JDBC Statement `
`org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL via JDBC Statement`
`Caused by: java.sql.SQLException: Cannot add foreign key constraint`
![image](https://user-images.githubusercontent.com/43334761/48557351-74594480-e921-11e8-8f99-7f62a6b42033.png)
`2018-11-15 21:03:23.905  WARN 9872 --- [           main] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL via JDBC Statement
`
`org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL via JDBC Statement`
`Caused by: java.sql.SQLException: Cannot add foreign key constraint`

**Comment by daydaywritecode** [comment]
**But there was no error in the end.**
`2018-11-15 21:03:29.300  INFO 9872 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2018-11-15 21:03:29.304  INFO 9872 --- [           main] com.ahau.BambootattanServerApplication   : Started BambootattanServerApplication in 21.443 seconds (JVM running for 22.261)
`

**Comment by liulianjushi** [comment]
recreate databases
